name=Raphael
version=1.0.1
author=robiduck
maintainer=robiduck
sentence=Raphael v1 Library
paragraph=A specialized hardware library developed for the Raphael board.
category=Device Control
url=https://github.com/robiduck/Raphael
architectures=avr