name=Raphael
version=1.0.0
author=robiduck
maintainer=robiduck
sentence=Raphael v1 Library
paragraph=Raphael robot kartı için gelistirilmis ozel donanim kutuphanesi.
category=Device Control
url=https://github.com/robiduck/raphael-board
architectures=avr